"""empty message

Revision ID: c1b518bf975e
Revises: 6fbdd7b29fbc
Create Date: 2019-08-30 14:21:32.713245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b518bf975e'
down_revision = '6fbdd7b29fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emoji', sa.Column('symbol', sa.String(length=255), nullable=True))
    op.drop_column('emoji', 'simbol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emoji', sa.Column('simbol', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('emoji', 'symbol')
    # ### end Alembic commands ###
